services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: grades_system_container
    environment:
      POSTGRES_USER: "${USER}"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "grades_system_development"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  bundle-volume:
